package exception_handling;

public class C {
	public static void main(String [] args) throws InterruptedException {
		int a=10;
		int b=0;
		try {
			   int c=a/b;	
		}
	catch(Exception S) {
	   System.out.println("exception handled");
	 
	}
			
	}	
	

}
